apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0 # https://hub.docker.com/r/nanajanashia/k8s-demo-app/tags
        ports:
        - containerPort: 3000 
        env:
          - name: USER_NAME
            valueFrom: 
              secretKeyRef:
                name: mongo-secret
                key: mongo-user
          - name: USER_PWD
            valueFrom: 
              secretKeyRef:
                name: mongo-secret
                key: mongo-password
          - name: DB_URL
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: mongo-url

--- 

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  # type: Service type
  # - Default = ClusterIP(an internal Service)
  # - NodePort
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      # nodePort: exposes the Service on each Node's IP at a static port
      # <NodeIP>:<NodePort>
      # node-port range: 30000-32767
      nodePort: 30100